version: '3'

volumes:
  pg_data_foodgram:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: kisame2011/foodgram_backend:latest
    restart: always
    env_file:
      - .env
    volumes:
      # Django соберет статику прямо сюда
      - static_volume:/app/backend_static/
      - media_volume:/app/media/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: kisame2011/foodgram_frontend:latest
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/frontend_static
    command:  sh -c "mkdir -p /frontend_static && cp -r /app/build/. /frontend_static/ && tail -f /dev/null"

  gateway:
    image: kisame2011/foodgram_gateway:latest
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/var/html/media/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./data/:/app/data/
    ports:
      - "127.0.0.1:9001:80"
    depends_on:
      - backend
      - frontend
