version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    image: kisame2011/foodgram_backend:latest
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - static:/app/media/media
    depends_on:
      - db
  frontend:
    image: kisame2011/foodgram_frontend:latest
    env_file:
      - .env
    command: cp -r /app/build/. /frontend_static/frontend/
    volumes:
      - static:/frontend_static/
  gateway:
    image: kisame2011/foodgram_gateway:latest
    volumes:
      - static:/var/html/
    depends_on:
      - backend
      - frontend
    ports:
      - "127.0.0.1:9001:80"
