server {
  listen 80;
  server_name ilyahost.sytes.net;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000;
  }

  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000;
  }

  location /static/admin/ {
    alias /var/html/django_static/admin/;
  }
  location /static/rest_framework/ {
    alias /var/html/django_static/rest_framework/;
  }

  location /media/ {
    alias /var/html/media/;
  }

  location / {
    root /var/html/frontend_static/;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}
