# Generated by Django 5.1.1 on 2026-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_short_link_recipe_short_link_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_link_code',
            field=models.CharField(default='default', max_length=10, unique=True, verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
    ]
