# Generated by Django 5.1.1 on 2026-06-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('author__username', 'user__username'), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
